In [1]:
print("a")

a


merhaba 
herhangi başka şeylerde yazılabilir 

 _italik_
 **kalın**
 
 _italik_
 **kalın**
 -

#NEDEN NUMPY

##alt başlıktır

In [1]:
a=[1,2,3,4]
b=[2,3,4,5,6]
a
b
# en sona hangi elemanı yazarsak onun içindeki elemanlar gelir
print(a,b)

[1, 2, 3, 4] [2, 3, 4, 5, 6]


In [22]:
ab=[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
np.nanmax(a)

4

In [25]:
a*b

array([ 2,  6, 12, 20])

In [26]:
a/b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [27]:
#numpy arrayi oluşturmak

In [2]:
import numpy as np 

In [3]:
a=np.array([1,2,3,4])

In [4]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14,2,4,5.18],dtype="float32")

array([3.14, 2.  , 4.  , 5.18], dtype=float32)

In [40]:
np.array([3.14,2,4,5.18],dtype="int")

array([3, 2, 4, 5])

In [41]:
#sıfırdan array oluşturma

In [4]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones(10, dtype="int")


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
np.full((3,5),2,dtype="float32")

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]], dtype=float32)

In [10]:
np.full((3,5),2,dtype="int")

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [9]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [17]:
np.arange(3,20,2,dtype="float32")

array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [51]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [53]:
np.random.normal(10,4,(3,4))#ortalaması=4 standart sapması=2

array([[17.01364526,  9.48514664,  7.22557776,  7.36110386],
       [ 5.96350357, 12.84417606, 12.32415928,  7.1825733 ],
       [10.2494541 , 12.40384299,  7.11565139,  3.4389514 ]])

In [33]:
np.full((2,10),1,dtype="float32")

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [55]:
np.random.randint(0,100,(3,3))

array([[25,  6, 74],
       [95, 15, 28],
       [39, 90, 70]])

In [1]:
import numpy as np


In [2]:
a=np.random.randint(10,20,(3,5))
a.sort()
a

array([[13, 14, 16, 18, 19],
       [11, 12, 16, 18, 19],
       [10, 10, 11, 11, 18]])

In [3]:
np.random.normal(10,5,(2,2))

array([[12.78521501, 21.54780658],
       [ 8.56487204,  5.99945867]])

In [4]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

* **ndim**
* **shape**
* **size**
* **dtype**

In [8]:
a=np.random.randint(5,20,size=25)
#a=np.random.randint(2,10,(3,5))
a.sort()
a
#eğer başlangıç değeri girmediysek 0 olarak algılar ama başlangıç değeri girersek o değerden başlatır.

array([ 7,  7,  8,  8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 12, 12, 13, 14,
       14, 15, 15, 16, 16, 18, 18, 19])

In [9]:
a.ndim#boyutu

1

In [10]:
 a.shape

(25,)

In [79]:
a.size#kaç sayı girmişsek onu döndürür

25

In [80]:
a.dtype

dtype('int32')

In [74]:
b=np.random.randint(10,size=(2,3))

In [75]:
b

array([[7, 2, 6],
       [1, 9, 5]])

In [69]:
b.ndim

2

In [70]:
b.shape

(2, 3)

In [71]:
b.size

6

In [72]:
b.dtype

dtype('int32')

#__Reshaping(yeniden sekillendirme)__
-

In [110]:
np.arange(1,19,2).reshape((3,3))
#__burda önemi olan kaç tane sayı girmişsek ona göre boyut ayarlamak__

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [111]:
a=np.arange(1,10).reshape(3,3)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a.ndim

2

In [114]:
b=a.reshape(1,9)
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [109]:
b.ndim

2

__ARRAY BİRLEŞTİRME(CONCATENATİON)__

In [11]:

import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6,7])

In [12]:
a=np.concatenate([x,y])
a

array([1, 2, 3, 4, 5, 6, 7])

In [120]:
a.ndim

1

In [121]:
z=np.array([7,8,9])

In [122]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 7, 8, 9])

##**iki boyut**

In [131]:
a=np.array([[1,2,3],
            [4,5,6]])

In [132]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
b=np.arange(10,16).reshape(2,3)
b

array([[10, 11, 12],
       [13, 14, 15]])

In [134]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15]])

In [135]:
np.concatenate([a,b],axis=0)#satır bazlı birleştirme yaptı

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15]])

In [136]:
np.concatenate([a,b],axis=1)#sutun bazlı birleştirme yaptı

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

**ARRAY AYIRMA(SPLİTTİNG)**

In [106]:
x=np.array([1,2,3,99,99,3,2,1])

In [116]:
np.split(x,[3,4])

[array([1, 2, 3]), array([99]), array([99,  3,  2,  1])]

In [112]:
a,b,c=np.split(x,[3,4])

In [113]:
a,b,c

(array([1, 2, 3]), array([99]), array([99,  3,  2,  1]))

In [114]:
b

array([99])

In [117]:
##iki boyutlu ayrıma

In [119]:
m=np.arange(16).reshape(4,4)

In [120]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [122]:
ust,alt=np.vsplit(m,[2])

In [123]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [124]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [128]:
sag,sol=np.hsplit(m,[2])

In [132]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [133]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# **SIRALAMA(SORTİNG)**


In [3]:
v=np.array([1,7,85,2,56,2])

In [4]:
v

array([ 1,  7, 85,  2, 56,  2])

In [5]:
np.sort(v)

array([ 1,  2,  2,  7, 56, 85])

In [6]:
v

array([ 1,  7, 85,  2, 56,  2])

In [7]:
v.sort()

In [8]:
v

array([ 1,  2,  2,  7, 56, 85])

In [9]:
##iki boyutlu array sıralama

In [10]:
m=np.random.normal(20,5,(3,3))

In [11]:
m

array([[14.6827825 , 21.51566237, 14.65342563],
       [19.16219932, 19.90326014, 22.14189652],
       [10.6309259 , 25.46873159, 19.93140725]])

In [12]:
m.sort()

In [13]:
m

array([[14.65342563, 14.6827825 , 21.51566237],
       [19.16219932, 19.90326014, 22.14189652],
       [10.6309259 , 19.93140725, 25.46873159]])

In [14]:
np.sort(m,axis=1)

array([[14.65342563, 14.6827825 , 21.51566237],
       [19.16219932, 19.90326014, 22.14189652],
       [10.6309259 , 19.93140725, 25.46873159]])

In [15]:
np.sort(m,axis=0)

array([[10.6309259 , 14.6827825 , 21.51566237],
       [14.65342563, 19.90326014, 22.14189652],
       [19.16219932, 19.93140725, 25.46873159]])

In [16]:
m

array([[14.65342563, 14.6827825 , 21.51566237],
       [19.16219932, 19.90326014, 22.14189652],
       [10.6309259 , 19.93140725, 25.46873159]])

In [17]:
m=np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.sort(m,axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.split(m,[2,3])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([], shape=(0, 3), dtype=int32)]

In [20]:
a=np.random.randint(1,10,(3,3))

In [21]:
a

array([[5, 8, 5],
       [7, 8, 9],
       [8, 8, 9]])

In [22]:
b=np.concatenate([a,m])

In [23]:
b

array([[5, 8, 5],
       [7, 8, 9],
       [8, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a=np.hsplit(m,[2])

In [25]:
a

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [26]:
a=np.vsplit(m,[3])
a

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([], shape=(0, 3), dtype=int32)]

In [27]:
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])
a4=np.array([[[1,2,3],[4,5,6],[9,8,7],[6,5,4]]])

In [28]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a4

array([[[1, 2, 3],
        [4, 5, 6],
        [9, 8, 7],
        [6, 5, 4]]])

In [30]:
a3[1:2,1:2]

array([[5]])

In [31]:
a3[1:,:1]

array([[4],
       [7]])

In [32]:
a4[1:,:2]

array([], shape=(0, 2, 3), dtype=int32)

In [33]:
git --version


NameError: name 'git' is not defined